### ISSUE TITLE
Anchor inside li

### ISSUE THREAD

**Issue by fefno** [glidejs/glide#128]
I have an anchor inside the &lt;li class="glide__slide"&gt; and i have to click twice to go to link instead. Why?

**Comment by jedrzejchalubek** [comment]
The problem occurs. Everything worked while ago, but now it changed.

Need to check that and will be fixed in next realase.

**Comment by jedrzejchalubek** [comment]
Could you test it out with [v2.0.6](https://github.com/jedrzejchalubek/Glide.js/tree/v2.0.6) branch?

**Comment by fefno** [comment]
Well, it worked but still has some bugs. In Chrome (v.46), there's a little delay to redirect.

**Comment by jedrzejchalubek** [comment]
Should be fine in v2.0.6 realese.

**Comment by Loac-fr** [comment]
Hi, i'm not opening an issue, i'm too shy, but I had a problem recently that I think could be related :)
I had a title (span, not anchor tag) on top of an image with a click event on it (to open a modal)
I wanted that on click the slider paused (slider_api.pause() )

But everytime, the slider resumed autoplay for no apparent reason.
I discovered that all click events seem to be prevented by triggering "swipeMove" (line 1468)

I fixed it by using "mousedown" instead of click to bypass it, but that behavior doesn't seem right.
Once again it could be something else, but 'click' event doesn't work, and 'mousedown' seems to fix it.
Or the issue could come from automatic autoplay after swipe ?

Anyway, I think you should be able to have click events inside slides :)

Also (but could be a problem on my end) I ended up having a ton of click events bound to the Glide Track after swipe.

To conclude, sorry for the long comment, and big thanks for the plugin :+1:

**Comment by jedrzejchalubek** [comment]
I'll look into it deeply, in free time. For now I have one advice:

If inside slider you have a lot of anchors/other events, it is better to turn off `dragDistance: false` option. Touch events will be still active.

**Comment by bfintal** [comment]
This happens to me too. You have to click twice on a normal anchor link. It doesn't happen if the carousel hasn't moved to the next slide yet. Turning off `dragDistance` fixes it. But it would be best if this worked with it on.
