### ISSUE TITLE
Aim towards ES6

### ISSUE THREAD

**Issue by jedrzejchalubek** [glidejs/glide#169]
The current modular structure is fair simple for conversion to classes, but it will entail to rely on some sort of bundler. This probably entails an increase in weight for end file.

More bold proposition is also to abandon jQuery dependency.

What do you think?

---

Proposes:

- [x] Provide as module for loaders/bundlers (AMD, CommonJS, ES6 Import etc.)
- [x] Convert to the ES6 Classes
- [x] Abbadon jQuery

**Comment by marcwieland95** [comment]
Some thoughts for the future after 1500 stars 😉

Using classes would be nice. While the code is already using a quite modular approach, this would be indeed not that hard.

Moving away from jQuery is understandable, because a lot other libraries are trying to avoid it. On the other hand, a lot of front-end developers are still using jQuery in their projects. So they're including jQuery anyways. From a developer perspective, jQuery doesn't offer huge advantages compared to plain javascript these days. A move would be a lot of work - rebuild from ground number 3, I guess.

**Comment by krishaamer** [comment]
This would be super nice!

**Comment by jedrzejchalubek** [comment]
[`v3.0.0`](https://github.com/glidejs/glide/releases/tag/v3.0.0) release is here 🎉
