### ISSUE TITLE
Next slide - set the number of slides to advance

### ISSUE THREAD

**Issue by lefty55104** [glidejs/glide#201]
If I have a carousel that displays 2 slides at a time (using the default settings for everything else), is there a way to have the next/previous arrows advance more than one slide at a time? In this specific case, I'd like to advance/reverse 2 at a time.

**Comment by jedrzejchalubek** [comment]
Unfortunately currently, there isn't any built-in option for this.

You probably can create this functionality by making an extension or using API.

**Comment by pateketrueke** [comment]
Hi, I thought I was falling in the same issue but my solution was pretty straight-forward.

Instead of placing one item per slide I opted to place two items per slide, and that also gave me more room for improvements, i.e. both items can be placed vertically on small screens and horizontally on larger screens.

**Comment by mehigh** [comment]
@lefty55104 you might want to view the contribution here: https://github.com/glidejs/glide/issues/252 this added the possibility to slide properly using the API according to the number of items per page displayed. It might hint you onto what would a solution for your custom needs could look like.

**Comment by jedrzejchalubek** [comment]
Released under v3.5.0
