### ISSUE TITLE
Problem with body margin:0

### ISSUE THREAD

**Issue by nicoladl** [glidejs/glide#203]
Hi guys!
I have some problem with Glide inside a body with margin 0.
I provide a Pen https://codepen.io/nicoladelazzari/pen/pVoVVz

If you comment the body margin 0 glide width fit correctly.
Any advice?

**Comment by RShalman** [comment]
Hi, nicoladl,

Could you please expand more on the result you're trying to achieve?

For now I can only see that if we comment body's `margin` - we only get those margins at the left and right of slider.

**Comment by gokul0** [comment]
Hi, nicoldal, 

You have specified the same styling for body with `margin : 0` twice. If you could remove the former one, you will be able to see the results better. This is an intended behaviour of css and so I do not see a problem here.

**Comment by nicoladl** [comment]
Sorry but I realized now that pen not replicate the error.
I try to post an image:
<img width="1316" alt="schermata 2018-04-19 alle 08 25 46" src="https://user-images.githubusercontent.com/2022727/38974689-5ae4dde6-43ab-11e8-9998-1da213fea0b6.png">

As you can see the width is not fitting the window width. After a manual resize of the browser Glide fit correctly.

I'm importing Glide with standard ES module:

```
import Glide from '@glidejs/glide'

new Glide('.glide', {
  gap: 0
}).mount()
```

What I'm doing wrong?

**Comment by jedrzejchalubek** [comment]
This margin is can caused by scrollbar, which disappears after applying CSS styles. At this point, glide may already calculated all dimensions. At a website with real content, this probably won't be a problem.

Maybe try to initialize glide at the end of a `<body>`?

**Comment by nicoladl** [comment]
Thank @jedrzejchalubek

This workaround works for me, but is not the best way to resolve this issue IMHO.
```
setTimeout(() => {
  new Glide('.glide', {
    gap: 0
  }).mount()
}, 1000)
```
Ho can I initialize glide at the end of the body with webpack?

**Comment by aguilera51284** [comment]
I also have that problem. The solution apparently is to do 'resize' after the mount. But I do not know how to do that, the documentation does not indicate
:(

**Comment by Stolzenhain** [comment]
Hey @aguilera51284 – you can use the [event dispatcher as described here](/glidejs/glide/issues/274).

The issue is caused by scrollbars on the `<body>` element though – they probably aren't present on init and cause the slides to be calculated too wide – and overlapping later on.

This can be easily prevented by enforcing scrollbars via

~~~
body {
  overflow-y: scroll;
}
~~~

**Comment by lifeinchords** [comment]
@Stolzenhain: `overflow` css did not work unfortunately.
@nicoladl's solution does. 
I'm not sure how to use the event dispatcher to resize .. can you please share more info?

**Comment by Stolzenhain** [comment]
> @Stolzenhain: `overflow` css did not work unfortunately.
> @nicoladl's solution does.
> I'm not sure how to use the event dispatcher to resize .. can you please share more info?

Hello! Yes, removing the gap calculation worked for us as well but was no option sadly.

The reason is correctly described by @jedrzejchalubek: Initializing the slide before the rest of the page is rendered – having no scrollbar at this stage, thus rendering the width incorrectly. Resizing triggers a recalculation, fixing the slide.

We ran the init script lazily – equalling a finished pageload, thus calculating the width correctly – now including the scrollbar.

The custom event dispatcher … I forgot how that worked. You had to register it yourself, so I guess you could trigger the recalculation after pageload – but then you could just trigger the script later yourself either.

**Comment by czyngis-git** [comment]
> This margin is can caused by scrollbar, which disappears after applying CSS styles. At this point, glide may already calculated all dimensions. At a website with real content, this probably won't be a problem.
> 
> Maybe try to initialize glide at the end of a `<body>`?

Initializing glide.js at the end of ```body``` solved this problem in my case. What a head cache... Too bad i did not look here first :/ Thanks
