### ISSUE TITLE
Changing perView and peek using update()

### ISSUE THREAD

**Issue by davidfig** [glidejs/glide#265]
I'm trying to change the perView and peek options during a resize. The carousel, however, is not updating to reflect these changes. Is this scenario supported?

Here's my code:

```js
const PADDING = 40
const THROTTLE = 50
let glide, last

function options()
{
    const width = document.getElementsByClassName('screen')[0].offsetWidth + PADDING
    const perView = Math.floor(window.innerWidth / width)
    const peek = perView === 1 ? width * 0.3 : 0
    return {
        type: 'carousel',
        focusAt: 'center',
        autoplay: 5000,
        perView,
        peek
    }
}

function create()
{
    glide = new Glide('.glide', options()).mount()
}

function resize()
{
    const now = Date.now()
    if (!last || now - last > THROTTLE)
    {
        glide.update(options())
        last = now
    }
}

window.addEventListener('load', create)
window.addEventListener('resize', resize)
```
Thanks!

**Comment by davidfig** [comment]
For now I'm destroying and recreating. Not ideal but works fine.

**Comment by jedrzejchalubek** [comment]
`update` call is a resources costly action. I don't know if calling it on resize event (even when throttled) is not too much for the library to keep up with updates of a slider. I doesn't done these kinds of tests. Some kind of jsfiddle to play with it would be helpful.

Is dynamic peeking (based on browser width) a key point? You can easily use `breakpoints` options with multiple points.

**Comment by cybafelo** [comment]
I overcame this problem btw by registering a Glide resize event, binding the glide object to the event handler and changing the settings object via 'this' reference, and passing my own objects which contain my application variables called mySettings like this:

```
...
const mySettings = {/*...my application state...*/};
...
let glide = new Glide(
    '.glide',
    {
        ...
        'perView' : 1
    }
);

glide.on(
   'resize',
   function(mySettings) {
      return function() {
         //change perView here based on mySettings like this:
         this.settings.perView = mySettings.valueForPerView;
         this.update();
      }.bind(glide)
   }(mySettings)
)

glide.mount();
```
This works - before that I had to destroy / re-create the entire widget.

The reason is because glide uses settings object in Breakpoints passed by reference and doesn't use updated settings object. Manually setting settings on glide object also doesn't work outside of the event handler. (tested this endlessly)

**Comment by quinlo** [comment]
I found this to be pretty straightforward using the resize event coupled with the update method:

glide.on(
    'resize',
    function() {
        glide.update({ peek: (window.innerWidth - 1000) / 2 })
    }
)
