### ISSUE TITLE
Enhanced support for non-integer `perView` values

### ISSUE THREAD

**Issue by slavanossar** [glidejs/glide#490]
It is currently possible to set `perView` to a non-integer value to achieve a peek effect:

![image](https://user-images.githubusercontent.com/7077600/82407765-6273d700-9aad-11ea-8a4b-8ae947fabe93.png)

Slide width calculations work as expected, but when using `bound: true` the translation limits are calculated incorrectly, since [the `perView` number converted to an integer when calculating `Run.length`](https://github.com/glidejs/glide/blob/e894ec359668df58a41568619d8ed33cc941916c/src/components/run.js#L310-L330).

![image](https://user-images.githubusercontent.com/7077600/82409316-c946bf80-9ab0-11ea-80e0-29c139f8bf23.png)

I hoped a simple switch to the `toFloat` helper function might have fixed it, but it looks like there are more calculations being done elsewhere. I'm happy to figure out the maths and create a PR if I can have some guidance on where in the source the other calculations are done.

Thanks

**Comment by slavanossar** [comment]
Sorry just realised there's a `peek` option, my bad.

**Comment by albanyacademy** [comment]
peek isn't relative though, you define it as pixels. this means you have to have a symmetrical layout. in general, having a decimal for perView *shouldn't* break the slider's behaviour. Designers must be satiated. Assymetrical designs for the designer god, n'yah! n'yah!

Anyway, what's interesting about the perView calculation is that it's defined by its container width - and I'm going to reference Bootstrap containers for sake of ease here - so if you have a container with a max-width of 1200px containing a glide slider, your perview is divisible by that. You can get some pretty interesting stuff from this as a result, including getting a slide that's bound to the container but extends beyond the viewport by setting overflow:visible on the slide track. example:

![glides-1](https://user-images.githubusercontent.com/4943290/89352073-28f04800-d668-11ea-9a17-467c11dec26c.png)

In the example, the perview is (ostensibly) set to 1.75 - we get a nice overhang on the right side on page load, designers love this and I get a nice bonus. The problem arises in the bottom, when dragging all the way to the end - it *doesn't* stop at the right-hand bound if the perView is a decimal, only a full number. What *does* happen is the default behaviour, which is the last slide will sit perfectly at the left-hand side bounds, which makes me think *bounds* must be ignored for some reason (if it was a layout bug it probably would sit weird at the last bound).

But due to the presence of *peek*, I'd gather none of this cool stuff is intended behaviour. But peek doesn't work as a truly responsive thing either - what if my gliderslider is within a 1200px container, but I want that bad boy to extend all the way across the right side of the page, regardless of how big it gets? I can't just throw in a fancy css calc() (which I have gotten *extremely* good at, designers love me), and while having it as a prop in breakpoints would serve some use cases it definitely doesn't serve them all.

In the meantime I'll probably try to just hack some margins so my designers continue lavishing me with praise, but it would be nice to get the perView calculation fixed so decimals doesn't inexplicably break other options.

**Comment by albanyacademy** [comment]
similar issue: https://github.com/glidejs/glide/issues/493#issuecomment-643454849
