### ISSUE TITLE
Dynamically created slides

### ISSUE THREAD

**Issue by rihok** [glidejs/glide#71]
The slider doesn't seem to initialize properly when the slides are created dynamically with jquery beforehand.

Any ideas?

**Comment by idesigns-studio** [comment]
Hello! I am having the same problem. When the window resizes, the width is adjusted to the correct fashion, but on load, it stacks up to the left. Since i don't really understand Javascript, could you give me the code for forcing a recalculation? I tried glide.reinit(); in many ways in my default start code, but it just duplicates the content.

**Comment by chrischen** [comment]
There doesn't seem to be a reinit method anymore. What's the correct way to reinit now?

**Comment by vcastro45** [comment]
@chrischen Did you find the solution ?

**Comment by kylerberry** [comment]
For those interested, it's not the most efficient way to resolve this but works for me.

I tried `this.gliderInstance.mount()` which fixes the new slide width, but it doesn't update the navigation as OP mentioned.

Now, I fully destroy the instance and mount a new one anytime slides are added / removed.

```
// ...on add slide
this.gliderInstance.destroy()
this.gliderInstance = new Glide(rootEl)
```
